name = "xugou-backend"
main = "src/index.ts"
compatibility_date = "2025-03-10"
compatibility_flags = ["nodejs_compat"]

# 添加定时触发器，每分钟执行一次监控检查
[triggers]
crons = ["* * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "uptime"
database_id = "a17b72af-d1e4-45ac-8b2a-33e7e2a633cf"

[version_metadata]
binding = "CF_VERSION_METADATA"
